version: '3.7'
services:
  backend:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    command: python backend/live_like_tree/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.env.dev
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
    command: ng serve  --host=0.0.0.0 --port 4200
    volumes:
      - ./usr/src/app/frontend/node_modules
    ports:
      - 4200:4200
    depends_on:
      - backend
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=live_like_tree_user
      - POSTGRES_PASSWORD=FKn2fiNflka1f
      - POSTGRES_DB=live_like_tree_db
volumes:
  postgres_data: