version: '3.7'
services:
  backend:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    command: python ./live_like_tree/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=live_like_tree_user
      - POSTGRES_PASSWORD=FKn2fiNflka1f
      - POSTGRES_DB=live_like_tree_db
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    command: ng serve
    volumes:
      - /usr/src/app/frontend/node_modules
    ports:
      - 4200:4200
volumes:
  postgres_data: