version: '3.7'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    command: sh -c "python backend/live_like_tree/manage.py runserver 0.0.0.0:8000 ; cd frontend && ng serve  --host=0.0.0.0 --port 4200"
    volumes:
      - ./backend/:/usr/src/app/backend/
    ports:
      - 8000:8000
      - 4200:4200
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=live_like_tree_user
      - POSTGRES_PASSWORD=FKn2fiNflka1f
      - POSTGRES_DB=live_like_tree_db
  iot:
    build: 
        context: ./iot
        dockerfile: Dockerfile
    command: python emulator.py
    depends_on:
      - web
volumes:
  postgres_data: